pkill -f "python3 /mnt/jfs*"
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=A,AA,AAL,AAMC,AAME,AAN,AAOI,AAON,AAP,AAPL,AAT,AAU,AAWW,AAXN,AB,ABBV,ABC,ABCB,ABEO,ABG,ABIO,ABM,ABMD,ABR,ABT,ABTX,ABUS,AC,ACA,ACAD,ACAM,ACB,ACBI,ACC,ACCD,ACCO,ACEL,ACER,ACGL,ACHC,ACHV,ACI,ACIA,ACIU,ACIW,ACLS,ACM,ACMR,ACN&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 1 &
echo 1/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=ACNB,ACOR,ACRE,ACRS,ACRX,ACST,ACTG,ACU,ACY,ADBE,ADC,ADCT,ADES,ADI,ADIL,ADM,ADMA,ADMP,ADMS,ADNT,ADP,ADPT,ADRO,ADS,ADSK,ADSW,ADT,ADTN,ADTX,ADUS,ADVM,ADXS,AE,AEE,AEGN,AEHR,AEIS,AEL,AEM,AEMD,AEO,AEP,AER,AERI,AES,AESE,AEY,AEYE,AEZS&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 2 &
echo 2/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=AFG,AFH,AFI,AFIB,AFIN,AFL,AFMD,AFYA,AG,AGBA,AGCO,AGE,AGEN,AGFS,AGI,AGIO,AGLE,AGM,AGM.A,AGMH,AGNC,AGO,AGR,AGRO,AGRX,AGS,AGTC,AGX,AGYS,AHC,AHCO,AHH,AHPI,AHT,AI,AIG,AIHS,AIKI,AIM,AIMC,AIMT,AIN,AINC,AIR,AIRG,AIRI,AIRT,AIT,AIV&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 3 &
echo 3/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=AIZ,AJG,AJRD,AJX,AKAM,AKBA,AKCA,AKER,AKR,AKRO,AKTS,AKUS,AL,ALAC,ALB,ALBO,ALC,ALCO,ALDX,ALE,ALEC,ALEX,ALG,ALGN,ALGT,ALIM,ALJJ,ALK,ALKS,ALL,ALLE,ALLK,ALLO,ALLT,ALLY,ALNA,ALNY,ALOT,ALPN,ALRM,ALRN,ALRS,ALSK,ALSN,ALT,ALTA,ALTG,ALTM,ALTR&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 4 &
echo 4/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=ALUS,ALV,ALVR,ALX,ALXN,ALXO,ALYA,AM,AMAG,AMAL,AMAT,AMBA,AMBC,AMC,AMCI,AMCR,AMCX,AME,AMED,AMEH,AMG,AMGN,AMH,AMK,AMKR,AMN,AMNB,AMOT,AMP,AMPE,AMPH,AMPY,AMRB,AMRC,AMRH,AMRK,AMRS,AMRX,AMS,AMSC,AMSF,AMSWA,AMT,AMTB,AMTBB,AMTD,AMTI,AMTX,AMWD&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 5 &
echo 5/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=AMZN,AN,ANAB,ANAT,ANDA,ANDE,ANET,ANF,ANGI,ANGO,ANH,ANIK,ANIP,ANIX,ANNX,ANSS,ANTM,ANVS,ANY,AON,AOS,AOSL,AOUTV,AP,APA,APAM,APD,APDN,APEI,APEN,APEX,APG,APH,APHA,APLE,APLS,APLT,APM,APO,APOG,APPF,APPN,APPS,APRE,APRN,APT,APTO,APTS,APTV&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 6 &
echo 6/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=APTX,APVO,APWC,APXT,APYX,AQB,AQMS,AQN,AQST,AQUA,AR,ARA,ARAV,ARAY,ARC,ARCB,ARCC,ARCE,ARCH,ARCO,ARCT,ARD,ARDS,ARDX,ARE,AREC,ARES,ARGO,ARI,ARKR,ARL,ARLO,ARLP,ARMK,ARMP,ARNA,ARNC,AROC,AROW,ARPO,ARQT,ARR,ARTL,ARTNA,ARTW,ARVN,ARW,ARWR,ARYA&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 7 &
echo 7/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=ARYB,ASB,ASC,ASFI,ASGN,ASH,ASIX,ASM,ASMB,ASPN,ASPS,ASPU,ASRT,ASRV,ASTC,ASTE,ASUR,ASYS,AT,ATAX,ATCO,ATCX,ATEC,ATEN,ATEX,ATGE,ATH,ATHX,ATI,ATIF,ATKR,ATLC,ATLO,ATNI,ATNM,ATNX,ATO,ATOM,ATOS,ATR,ATRA,ATRC,ATRI,ATRO,ATRS,ATSG,ATTO,ATUS,ATVI&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 8 &
echo 8/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=ATXI,AUB,AUBN,AUDC,AUG,AUMN,AUPH,AUTO,AUY,AVA,AVAV,AVB,AVCO,AVCT,AVD,AVEO,AVGO,AVGR,AVID,AVLR,AVNS,AVNT,AVNW,AVRO,AVT,AVTR,AVXL,AVY,AVYA,AWH,AWI,AWK,AWR,AWRE,AWX,AX,AXAS,AXDX,AXGN,AXGT,AXL,AXLA,AXNX,AXP,AXR,AXS,AXSM,AXTA,AXTI&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 9 &
echo 9/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=AXU,AY,AYI,AYLA,AYRO,AYTU,AYX,AZEK,AZO,AZPN,AZRE,AZRX,AZZ,B,BA,BAC,BAH,BAM,BANC,BAND,BANF,BANR,BAP,BASI,BATL,BATRA,BATRK,BAX,BB,BBBY,BBCP,BBDC,BBGI,BBI,BBIO,BBQ,BBSI,BBU,BBW,BBX,BBY,BC,BCBP,BCC,BCDA,BCE,BCEI,BCEL,BCLI&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 10 &
echo 10/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=BCML,BCO,BCOM,BCOR,BCOV,BCOW,BCPC,BCRX,BCSF,BCTF,BDC,BDGE,BDL,BDN,BDR,BDSI,BDTX,BDX,BE,BEAM,BEAT,BECN,BELFA,BELFB,BEN,BEP,BEPC,BERY,BF.A,BF.B,BFAM,BFC,BFIN,BFS,BFST,BFYT,BG,BGCP,BGFV,BGI,BGS,BGSF,BH,BH.A,BHAT,BHB,BHC,BHE,BHF&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 11 &
echo 11/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=BHLB,BHR,BHTG,BHVN,BIG,BIGC,BIIB,BILL,BIMI,BIO,BIO.B,BIOC,BIOL,BIOX,BIP,BIPC,BJ,BJRI,BK,BKCC,BKD,BKE,BKEP,BKH,BKI,BKNG,BKR,BKSC,BKTI,BKU,BKYI,BL,BLBD,BLCM,BLD,BLDP,BLDR,BLFS,BLI,BLIN,BLK,BLKB,BLL,BLMN,BLNK,BLPH,BLU,BLUE,BLX&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 12 &
echo 12/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=BMCH,BMI,BMO,BMRA,BMRC,BMRG,BMRN,BMTC,BMY,BNED,BNFT,BNGO,BNS,BNSO,BNTC,BOCH,BOH,BOKF,BOMN,BOOM,BOOT,BORR,BOSC,BOTJ,BOX,BOXL,BPFH,BPMC,BPMP,BPOP,BPRN,BPT,BPTH,BPY,BPYU,BR,BRBR,BRBS,BRC,BREW,BRG,BRID,BRK.A,BRK.B,BRKL,BRKR,BRKS,BRLI,BRMK&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 13 &
echo 13/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=BRN,BRO,BROG,BRP,BRPA,BRQS,BRT,BRX,BRY,BSBK,BSET,BSGM,BSIG,BSM,BSQR,BSRR,BSTC,BSVN,BSX,BTAI,BTBT,BTE,BTG,BTN,BTU,BURL,BUSE,BV,BW,BWA,BWB,BWEN,BWFG,BWL.A,BWMX,BWXT,BX,BXC,BXG,BXMT,BXP,BXRX,BXS,BY,BYD,BYFC,BYND,BYSI,BZH&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 14 &
echo 14/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=C,CAAP,CAAS,CABA,CABO,CAC,CACC,CACI,CADE,CAE,CAG,CAH,CAI,CAKE,CAL,CALA,CALB,CALM,CALX,CAMP,CAMT,CAPL,CAPR,CAR,CARA,CARE,CARG,CARR,CARS,CARV,CASA,CASH,CASI,CASS,CASY,CAT,CATB,CATC,CATM,CATO,CATY,CB,CBAN,CBAT,CBAY,CBB,CBFV,CBIO,CBL&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 15 &
echo 15/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CBLI,CBMB,CBMG,CBNK,CBOE,CBPO,CBRE,CBRL,CBSH,CBT,CBTX,CBU,CBZ,CC,CCAC,CCAP,CCB,CCBG,CCC,CCCL,CCEP,CCF,CCH,CCI,CCJ,CCK,CCL,CCLP,CCMP,CCNC,CCNE,CCO,CCOI,CCR,CCRC,CCRN,CCS,CCX,CCXI,CCXX,CDAY,CDE,CDEV,CDK,CDLX,CDMO,CDNA,CDNS,CDOR&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 16 &
echo 16/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CDR,CDTX,CDW,CDXC,CDXS,CDZI,CE,CECE,CEI,CEIX,CEL,CELC,CELH,CELP,CEMI,CENT,CENTA,CENX,CEQP,CERC,CERN,CERS,CETV,CETX,CEVA,CF,CFB,CFBI,CFBK,CFFA,CFFI,CFFN,CFG,CFMS,CFR,CFRX,CFX,CG,CGA,CGBD,CGC,CGEN,CGIX,CGNX,CGRO,CHAP,CHAQ,CHCI,CHCO&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 17 &
echo 17/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CHCT,CHD,CHDN,CHE,CHEF,CHEK,CHFS,CHGG,CHH,CHKP,CHMA,CHMG,CHMI,CHNG,CHNR,CHPM,CHRA,CHRS,CHRW,CHS,CHTR,CHUY,CHWY,CHX,CI,CIA,CIDM,CIEN,CIGI,CIIC,CIM,CINF,CINR,CIO,CIR,CIT,CIVB,CIX,CIZN,CJJD,CKH,CKPT,CKX,CL,CLAR,CLB,CLBK,CLBS,CLCT&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 18 &
echo 18/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CLDB,CLDR,CLDT,CLDX,CLEU,CLF,CLFD,CLGX,CLH,CLI,CLIR,CLMT,CLNC,CLNE,CLNY,CLPR,CLPS,CLPT,CLR,CLRB,CLRO,CLS,CLSD,CLSK,CLSN,CLUB,CLVS,CLW,CLWT,CLX,CLXT,CM,CMA,CMBM,CMC,CMCL,CMCO,CMCSA,CMCT,CMD,CME,CMG,CMI,CMLS,CMO,CMP,CMPI,CMPR,CMRE&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 19 &
echo 19/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CMRX,CMS,CMT,CMTL,CNA,CNBKA,CNC,CNCE,CNDT,CNET,CNFR,CNHI,CNI,CNK,CNMD,CNNB,CNNE,CNO,CNOB,CNP,CNQ,CNR,CNS,CNSL,CNSP,CNST,CNTG,CNTY,CNX,CNXM,CNXN,CO,COCP,CODA,CODI,CODX,COF,COFS,COG,COHN,COHR,COHU,COKE,COLB,COLD,COLL,COLM,COMM,CONE&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 20 &
echo 20/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CONN,COO,COOP,COP,COR,CORE,CORR,CORT,COST,COTY,COUP,COWN,CP,CPA,CPAA,CPAH,CPB,CPE,CPF,CPG,CPHC,CPHI,CPIX,CPK,CPLG,CPLP,CPRI,CPRT,CPRX,CPS,CPSH,CPSI,CPSS,CPST,CPT,CPTA,CQP,CR,CRAI,CRBP,CRD.A,CRD.B,CRDF,CREE,CREG,CREX,CRHM,CRI,CRIS&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 21 &
echo 21/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CRK,CRL,CRM,CRMD,CRMT,CRNC,CRNT,CRNX,CRON,CROX,CRS,CRSA,CRSP,CRT,CRTX,CRUS,CRVL,CRVS,CRWD,CRWS,CRY,CSBR,CSCO,CSGP,CSGS,CSII,CSIQ,CSL,CSLT,CSOD,CSPI,CSPR,CSSE,CSTE,CSTL,CSTM,CSTR,CSU,CSV,CSWC,CSWI,CSX,CTAS,CTB,CTBI,CTEK,CTG,CTHR,CTIB&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 22 &
echo 22/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CTIC,CTL,CTLT,CTMX,CTO,CTRA,CTRE,CTRM,CTRN,CTS,CTSH,CTSO,CTT,CTVA,CTXR,CTXS,CUB,CUBE,CUBI,CUE,CULP,CURO,CUTR,CUZ,CVA,CVBF,CVCO,CVCY,CVE,CVEO,CVET,CVGI,CVGW,CVI,CVLG,CVLT,CVLY,CVM,CVNA,CVR,CVS,CVU,CVV,CVX,CW,CWBC,CWBR,CWCO,CWEN&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 23 &
echo 23/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=CWEN.A,CWH,CWK,CWST,CWT,CXDC,CXDO,CXO,CXP,CXW,CYAN,CYBE,CYBR,CYCC,CYCN,CYD,CYH,CYRN,CYRX,CYTK,CZNC,CZR,CZWI,CZZ,D,DAC,DAIO,DAKT,DAL,DAN,DAR,DARE,DB,DBCP,DBD,DBI,DBX,DCI,DCO,DCOM,DCP,DCPH,DCTH,DD,DDD,DDOG,DDS,DE,DEA&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 24 &
echo 24/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=DECK,DEI,DELL,DENN,DESP,DFFN,DFIN,DFNS,DFPH,DFS,DG,DGICA,DGICB,DGII,DGLY,DGX,DHC,DHI,DHIL,DHR,DHT,DHX,DIN,DIOD,DIS,DISCA,DISCB,DISCK,DISH,DIT,DJCO,DK,DKL,DKNG,DKS,DLA,DLB,DLHC,DLNG,DLPH,DLPN,DLR,DLTH,DLTR,DLX,DMAC,DMLP,DMPI,DMRC&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 25 &
echo 25/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=DMS,DMTK,DMYT,DNB,DNKN,DNLI,DNN,DNOW,DOC,DOCU,DOGZ,DOMO,DOOO,DOOR,DORM,DOV,DOW,DOX,DPHC,DPW,DPZ,DRAD,DRE,DRH,DRI,DRIO,DRNA,DRQ,DRRX,DRTT,DS,DSGX,DSKE,DSPG,DSS,DSSI,DSWL,DSX,DT,DTE,DTEA,DTIL,DTSS,DUK,DUOT,DVA,DVAX,DVD,DVN&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 26 &
echo 26/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=DWSN,DX,DXC,DXCM,DXLG,DXPE,DXR,DXYN,DY,DYAI,DYNT,DZSI,EA,EAF,EARN,EARS,EAST,EAT,EB,EBAY,EBF,EBIX,EBMT,EBON,EBS,EBSB,EBTC,ECHO,ECL,ECOL,ECOM,ECOR,ECPG,ED,EDIT,EDNT,EDRY,EDSA,EDTK,EDUC,EEFT,EEX,EFC,EFOI,EFSC,EFX,EGAN,EGBN,EGHT&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 27 &
echo 27/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=EGLE,EGO,EGOV,EGP,EGRX,EGY,EHC,EHTH,EIC,EIDX,EIG,EIGI,EIGR,EIX,EKSO,EL,ELA,ELAN,ELF,ELLO,ELMD,ELOX,ELS,ELSE,ELTK,ELVT,ELY,EMAN,EMCF,EME,EMKR,EML,EMN,EMR,EMX,ENB,ENBL,ENDP,ENG,ENLC,ENLV,ENOB,ENPH,ENR,ENS,ENSG,ENSV,ENTA,ENTG&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 28 &
echo 28/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=ENTX,ENV,ENVA,ENZ,EOG,EOLS,EPAC,EPAM,EPAY,EPC,EPD,EPIX,EPM,EPR,EPRT,EPSN,EPZM,EQ,EQBK,EQC,EQH,EQIX,EQR,EQT,EQX,ERF,ERIE,ERII,EROS,ES,ESBA,ESBK,ESCA,ESE,ESEA,ESGR,ESI,ESLT,ESNT,ESP,ESPR,ESQ,ESRT,ESS,ESSA,ESSC,ESTA,ESTC,ESTE&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 29 &
echo 29/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=ESXB,ET,ETFC,ETH,ETM,ETN,ETNB,ETON,ETR,ETRN,ETSY,ETTX,EURN,EV,EVA,EVBG,EVBN,EVC,EVER,EVFM,EVGN,EVH,EVI,EVK,EVLO,EVOK,EVOL,EVOP,EVR,EVRG,EVRI,EVSI,EVTC,EW,EWBC,EXAS,EXC,EXEL,EXFO,EXK,EXLS,EXP,EXPC,EXPD,EXPE,EXPI,EXPO,EXPR,EXR&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 30 &
echo 30/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=EXTN,EXTR,EYE,EYEG,EYEN,EYES,EYPT,EZPW,F,FAF,FAMI,FANG,FARM,FARO,FAST,FAT,FATE,FB,FBC,FBHS,FBIO,FBIZ,FBK,FBM,FBMS,FBNC,FBP,FBRX,FBSS,FC,FCAP,FCAU,FCBC,FCBP,FCCO,FCCY,FCEL,FCF,FCFS,FCN,FCNCA,FCPT,FCRD,FCX,FDBC,FDP,FDS,FDUS,FDX&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 31 &
echo 31/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=FE,FEAC,FEIM,FELE,FENC,FET,FEYE,FF,FFBC,FFBW,FFG,FFHL,FFIC,FFIN,FFIV,FFNW,FFWM,FGBI,FGEN,FHB,FHI,FHN,FI,FIBK,FICO,FIS,FISI,FISK,FISV,FIT,FITB,FIVE,FIVN,FIX,FIXX,FIZZ,FL,FLDM,FLEX,FLGT,FLIC,FLIR,FLL,FLMN,FLNG,FLNT,FLO,FLOW,FLR&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 32 &
echo 32/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=FLS,FLT,FLWS,FLXN,FLXS,FMAO,FMBH,FMBI,FMC,FMCI,FMNB,FMTX,FN,FNB,FNCB,FND,FNF,FNHC,FNKO,FNLC,FNV,FNWB,FOCS,FOE,FOLD,FONR,FOR,FORD,FORK,FORM,FORR,FOSL,FOUR,FOX,FOXA,FOXF,FPAC,FPAY,FPH,FPI,FPRX,FR,FRAF,FRAN,FRBA,FRBK,FRC,FREE,FREQ&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 33 &
echo 33/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=FRG,FRGI,FRHC,FRME,FRO,FRPH,FRPT,FRT,FRTA,FSB,FSBW,FSCT,FSEA,FSFG,FSI,FSK,FSKR,FSLR,FSLY,FSM,FSP,FSRV,FSS,FSTR,FSV,FTAC,FTAI,FTCH,FTDR,FTEK,FTFT,FTHM,FTI,FTK,FTNT,FTS,FTSI,FTV,FUL,FULC,FULT,FUN,FUNC,FUSB,FUSN,FUV,FVAC,FVCB,FVE&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 34 &
echo 34/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=FVRR,FWONA,FWONK,FWRD,FXNC,G,GABC,GAIA,GAIN,GALT,GASS,GATX,GAU,GBCI,GBDC,GBIO,GBL,GBLI,GBR,GBT,GBX,GCBC,GCI,GCO,GCP,GD,GDDY,GDEN,GDOT,GDP,GDYN,GE,GEC,GECC,GEF,GEF.B,GEL,GEN,GENC,GEO,GEOS,GERN,GES,GEVO,GFED,GFF,GFL,GFN,GGG&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 35 &
echo 35/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=GH,GHC,GHIV,GHL,GHM,GHSI,GIB,GIFI,GIGM,GIII,GIK,GIL,GILD,GILT,GIS,GIX,GKOS,GL,GLAD,GLBS,GLBZ,GLDD,GLEO,GLG,GLIBA,GLMD,GLNG,GLOB,GLOG,GLOP,GLP,GLPI,GLRE,GLT,GLUU,GLW,GLYC,GM,GMBL,GMDA,GME,GMED,GMHI,GMLP,GMO,GMRE,GMS,GNCA,GNE&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 36 &
echo 36/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=GNK,GNL,GNLN,GNMK,GNPX,GNRC,GNRS,GNSS,GNTX,GNTY,GNUS,GNW,GO,GOCO,GOED,GOGL,GOGO,GOLD,GOLF,GOOD,GOOG,GOOGL,GOOS,GORO,GOSS,GPC,GPI,GPK,GPL,GPMT,GPN,GPOR,GPP,GPRE,GPRK,GPRO,GPS,GPX,GRA,GRAF,GRBK,GRC,GRIF,GRIL,GRIN,GRMN,GRNQ,GRNV,GROW&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 37 &
echo 37/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=GRPN,GRTS,GRTX,GRUB,GRWG,GS,GSAT,GSB,GSBC,GSBD,GSHD,GSIT,GSKY,GSL,GSM,GSMG,GSS,GSV,GT,GTE,GTEC,GTES,GTHX,GTIM,GTLS,GTN,GTN.A,GTS,GTT,GTX,GTY,GTYH,GURE,GV,GVA,GVP,GWB,GWGH,GWRE,GWRS,GWW,GXGX,GYRO,H,HA,HAE,HAFC,HAIN,HAL&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 38 &
echo 38/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=HALL,HALO,HAPP,HARP,HAS,HASI,HAYN,HBAN,HBB,HBCP,HBI,HBIO,HBM,HBMD,HBNC,HBP,HBT,HCA,HCAC,HCAT,HCC,HCCH,HCCI,HCCO,HCFT,HCHC,HCI,HCKT,HCSG,HD,HDS,HDSN,HE,HEAR,HEBT,HEC,HEES,HEI,HEI.A,HELE,HEP,HEPA,HES,HESM,HEXO,HFBL,HFC,HFFG,HFWA&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 39 &
echo 39/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=HGSH,HGV,HHC,HHT,HI,HIBB,HIFS,HIG,HIHO,HII,HIL,HIW,HJLI,HL,HLF,HLI,HLIO,HLIT,HLNE,HLT,HLX,HMG,HMHC,HMLP,HMN,HMNF,HMST,HMSY,HMTV,HNGR,HNI,HNNA,HNRG,HOFT,HOFV,HOG,HOLI,HOLX,HOMB,HOME,HON,HONE,HOOK,HOPE,HOTH,HOV,HP,HPE,HPP&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 40 &
echo 40/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=HPQ,HPR,HQI,HQY,HR,HRB,HRC,HRI,HRL,HROW,HRTG,HRTX,HSAQ,HSC,HSDT,HSIC,HSII,HSKA,HSON,HST,HSTM,HSTO,HSY,HT,HTA,HTBI,HTBK,HTBX,HTGC,HTGM,HTH,HTLD,HTLF,HTZ,HUBB,HUBG,HUBS,HUD,HUGE,HUM,HUN,HURC,HURN,HUSA,HUSN,HVBC,HVT,HVT.A,HWBK&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 41 &
echo 41/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=HWC,HWCC,HWKN,HWM,HXL,HY,HYAC,HYMC,HYRE,HZN,HZNP,HZO,IAA,IAC,IAG,IART,IBCP,IBEX,IBIO,IBKR,IBM,IBOC,IBP,IBTX,ICAD,ICBK,ICCC,ICCH,ICD,ICE,ICFI,ICHR,ICL,ICLR,ICON,ICPT,ICUI,IDA,IDCC,IDEX,IDN,IDRA,IDT,IDXG,IDXX,IDYA,IEA,IEC,IEP&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 42 &
echo 42/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=IESC,IEX,IFF,IFMK,IFRX,IFS,IGC,IGIC,IGMS,IGT,IHC,IHRT,IHT,III,IIIN,IIIV,IIN,IIPR,IIVI,IKNX,ILMN,ILPT,IMAC,IMAX,IMBI,IMGN,IMH,IMKTA,IMMR,IMMU,IMO,IMRA,IMTE,IMTX,IMUX,IMV,IMVT,IMXI,INBK,INCY,INDB,INDO,INFI,INFN,INFO,INFU,INGN,INGR,INMB&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 43 &
echo 43/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=INMD,INN,INO,INOD,INOV,INPX,INS,INSE,INSG,INSM,INSP,INSU,INSW,INT,INTC,INTG,INTT,INTU,INUV,INVA,INVE,INVH,INWK,INZY,IO,IONS,IOR,IOSP,IOVA,IP,IPAR,IPDN,IPG,IPGP,IPHI,IPI,IPOB,IPOC,IPV,IPWR,IQV,IR,IRBT,IRDM,IRET,IRIX,IRM,IRMD,IROQ&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 44 &
echo 44/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=IRT,IRTC,IRWD,ISBC,ISDR,ISEE,ISIG,ISNS,ISR,ISRG,ISSC,ISTR,IT,ITCI,ITGR,ITI,ITIC,ITOS,ITP,ITRG,ITRI,ITRM,ITRN,ITT,ITW,IVAC,IVC,IVR,IVZ,IZEA,J,JACK,JAGX,JAKK,JAMF,JAN,JAX,JAZZ,JBGS,JBHT,JBL,JBLU,JBSS,JBT,JCAP,JCI,JCOM,JCS,JCTCF&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 45 &
echo 45/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=JE,JEF,JELD,JFK,JHG,JIH,JILL,JJSF,JKHY,JLL,JMP,JNCE,JNJ,JNPR,JOB,JOE,JOUT,JPM,JRSH,JRVR,JVA,JW.A,JW.B,JWN,JWS,JYNT,K,KAI,KALA,KALU,KALV,KAMN,KAR,KBAL,KBH,KBLM,KBNT,KBR,KBSF,KDMN,KDP,KE,KELYA,KELYB,KEN,KEQU,KERN,KEX,KEY&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 46 &
echo 46/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=KEYS,KFFB,KFRC,KFS,KFY,KGC,KGJI,KHC,KIDS,KIM,KIN,KINS,KIQ,KIRK,KKR,KL,KLAC,KLDO,KLIC,KLR,KLXE,KMB,KMDA,KMI,KMPR,KMT,KMX,KN,KNDI,KNL,KNOP,KNSA,KNSL,KNX,KO,KOD,KODK,KOP,KOPN,KOR,KOS,KOSS,KPTI,KR,KRA,KRC,KREF,KRG,KRMD&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 47 &
echo 47/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=KRNT,KRNY,KRO,KROS,KRP,KRTX,KRUS,KRYS,KSS,KSU,KTB,KTCC,KTOS,KURA,KVHI,KW,KWR,KXIN,KZR,L,LAC,LACQ,LAD,LADR,LAKE,LAMR,LANC,LAND,LARK,LASR,LATN,LAUR,LAWS,LAZ,LAZY,LB,LBAI,LBC,LBRDA,LBRDK,LBRT,LBTYA,LBTYB,LBTYK,LC,LCA,LCI,LCII,LCNB&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 48 &
echo 48/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=LCTX,LCUT,LDL,LDOS,LE,LEA,LEAF,LECO,LEDS,LEE,LEG,LEGH,LEN,LEN.B,LEU,LEVI,LEVL,LFAC,LFUS,LFVN,LGC,LGF.A,LGF.B,LGIH,LGL,LGND,LGVW,LH,LHCG,LHX,LIFE,LII,LILA,LILAK,LIN,LINC,LIND,LIQT,LITE,LIVE,LIVK,LIVN,LIVX,LJPC,LKCO,LKFN,LKQ,LL,LLIT&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 49 &
echo 49/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=LLNW,LLY,LMAT,LMB,LMFA,LMND,LMNL,LMNR,LMNX,LMPX,LMRK,LMST,LMT,LNC,LNDC,LNG,LNN,LNT,LNTH,LOAC,LOAK,LOAN,LOB,LOCO,LODE,LOGC,LOGI,LOGM,LONE,LOOP,LOPE,LORL,LOVE,LOW,LPCN,LPG,LPI,LPLA,LPRO,LPSN,LPTH,LPTX,LPX,LQDA,LQDT,LRCX,LRMR,LRN,LSAC&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 50 &
echo 50/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=LSBK,LSCC,LSI,LSTR,LSXMA,LSXMB,LSXMK,LTBR,LTC,LTHM,LTRN,LTRPA,LTRPB,LTRX,LUB,LULU,LUMO,LUNA,LUV,LVGO,LVS,LW,LWAY,LXFR,LXP,LXRX,LXU,LYB,LYFT,LYL,LYRA,LYTS,LYV,LZB,M,MA,MAA,MAC,MACK,MAG,MAGS,MAIN,MAN,MANH,MANT,MANU,MAR,MARA,MARK&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 51 &
echo 51/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=MARPS,MAS,MASI,MAT,MATW,MATX,MAXR,MAYS,MBCN,MBI,MBII,MBIN,MBIO,MBOT,MBRX,MBUU,MBWM,MC,MCB,MCBC,MCBS,MCD,MCEP,MCF,MCFT,MCHP,MCHX,MCK,MCMJ,MCO,MCRB,MCRI,MCS,MCY,MD,MDB,MDC,MDCA,MDGL,MDIA,MDJH,MDLA,MDLY,MDLZ,MDP,MDRR,MDRX,MDT,MDU&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 52 &
echo 52/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=MDWD,MEC,MED,MEDP,MEDS,MEET,MEG,MEI,MEIP,MELI,MEOH,MERC,MESA,MET,METC,METX,MFA,MFAC,MFC,MFIN,MFNC,MG,MGA,MGEE,MGEN,MGI,MGIC,MGLN,MGM,MGNI,MGNX,MGP,MGPI,MGRC,MGTA,MGTX,MGY,MGYR,MHH,MHK,MHLD,MHO,MIC,MICT,MIDD,MIK,MIME,MIND,MIRM&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 53 &
echo 53/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=MIST,MITK,MITT,MJCO,MKC,MKC.V,MKGI,MKL,MKSI,MKTX,MLAB,MLAC,MLHR,MLI,MLM,MLND,MLP,MLR,MLSS,MLVF,MMAC,MMC,MMI,MMLP,MMM,MMP,MMS,MMSI,MMX,MMYT,MN,MNCL,MNDO,MNK,MNKD,MNLO,MNOV,MNPR,MNR,MNRL,MNRO,MNSB,MNST,MNTA,MNTX,MO,MOBL,MOD,MODN&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 54 &
echo 54/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=MOFG,MOG.A,MOG.B,MOGO,MOH,MORF,MORN,MOS,MOSY,MOTS,MOV,MOXC,MPAA,MPB,MPC,MPLX,MPW,MPWR,MPX,MR,MRAM,MRBK,MRC,MRCC,MRCY,MRIN,MRK,MRKR,MRLN,MRNA,MRNS,MRO,MRSN,MRTN,MRTX,MRUS,MRVL,MS,MSA,MSB,MSBI,MSCI,MSEX,MSFT,MSGE,MSGN,MSGS,MSI,MSM&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 55 &
echo 55/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=MSN,MSON,MSTR,MSVB,MTA,MTB,MTBC,MTC,MTCH,MTD,MTDR,MTEM,MTEX,MTG,MTH,MTN,MTNB,MTOR,MTR,MTRN,MTRX,MTSC,MTSI,MTSL,MTW,MTX,MTZ,MU,MUR,MUSA,MUX,MVBF,MVC,MVIS,MWA,MWK,MX,MXC,MXIM,MXL,MYE,MYFW,MYGN,MYL,MYO,MYOK,MYOS,MYOV,MYRG&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 56 &
echo 56/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=MYSZ,MYT,NAII,NAK,NAKD,NAOV,NARI,NAT,NATH,NATI,NATR,NAV,NAVB,NAVI,NBAC,NBEV,NBHC,NBIX,NBL,NBLX,NBN,NBR,NBRV,NBSE,NBTB,NBY,NC,NCBS,NCLH,NCMI,NCNO,NCR,NCSM,NDAQ,NDLS,NDRA,NDSN,NEE,NEM,NEO,NEOG,NEON,NEOS,NEP,NEPH,NEPT,NERV,NES,NESR&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 57 &
echo 57/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=NET,NETE,NEU,NEWA,NEWR,NEWT,NEX,NEXA,NEXT,NFBK,NFE,NFG,NFH,NFIN,NFLX,NG,NGD,NGHC,NGL,NGM,NGS,NGVC,NGVT,NH,NHC,NHI,NHLD,NHTC,NI,NICK,NINE,NJR,NK,NKE,NKLA,NKSH,NKTR,NKTX,NL,NLOK,NLS,NLSN,NLTX,NLY,NM,NMCI,NMFC,NMIH,NMM&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 58 &
echo 58/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=NMRD,NMRK,NMTR,NNA,NNBR,NNI,NNN,NNVC,NOA,NOC,NODK,NOG,NOMD,NOV,NOVA,NOVN,NOVS,NOVT,NOW,NP,NPA,NPK,NPO,NPTN,NR,NRBO,NRC,NREF,NRG,NRIM,NRIX,NRP,NRT,NRZ,NS,NSA,NSC,NSCO,NSEC,NSIT,NSP,NSPR,NSSC,NSTG,NSYS,NTAP,NTB,NTCT,NTEC&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 59 &
echo 59/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=NTGR,NTIC,NTIP,NTLA,NTN,NTNX,NTP,NTR,NTRA,NTRP,NTRS,NTST,NTUS,NTWK,NUAN,NUE,NURO,NUS,NUVA,NUZE,NVAX,NVCN,NVCR,NVDA,NVEC,NVEE,NVFY,NVGS,NVIV,NVMI,NVR,NVRO,NVST,NVT,NVTA,NVUS,NWBI,NWE,NWFL,NWGI,NWHM,NWL,NWLI,NWN,NWPX,NWS,NWSA,NX,NXE&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 60 &
echo 60/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=NXGN,NXPI,NXRT,NXST,NXTC,NXTD,NYCB,NYMT,NYMX,NYT,O,OAC,OAS,OBAS,OBCI,OBLG,OBLN,OBNK,OBSV,OC,OCC,OCFC,OCGN,OCN,OCSL,OCUL,OCX,ODC,ODFL,ODP,ODT,OEC,OEG,OESX,OFC,OFED,OFG,OFIX,OFLX,OFS,OGCP,OGE,OGEN,OGI,OGS,OHI,OI,OII,OIS&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 61 &
echo 61/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=OKE,OKTA,OLB,OLED,OLLI,OLN,OLP,OMC,OMCL,OMER,OMEX,OMF,OMI,OMP,ON,ONB,ONCS,ONCT,ONCY,ONDK,ONEM,ONEW,ONTO,ONTX,ONVO,OOMA,OPBK,OPCH,OPES,OPGN,OPHC,OPI,OPK,OPNT,OPOF,OPRT,OPRX,OPTN,OPTT,OPY,OR,ORA,ORBC,ORC,ORCC,ORCL,ORGO,ORGS,ORI&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 62 &
echo 62/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=ORIC,ORLY,ORMP,ORN,ORRF,ORSN,OSB,OSBC,OSG,OSH,OSIS,OSK,OSMT,OSPN,OSS,OSTK,OSUR,OSW,OTEL,OTEX,OTIC,OTIS,OTLK,OTRK,OTTR,OUT,OVBC,OVID,OVLY,OVV,OXBR,OXFD,OXM,OXSQ,OXY,OYST,OZK,PAA,PAAS,PACB,PACD,PACK,PACQ,PACW,PAE,PAG,PAGP,PAGS,PAHC&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 63 &
echo 63/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=PAND,PANL,PANW,PAR,PARR,PASG,PATI,PATK,PAVM,PAYC,PAYS,PAYX,PB,PBA,PBCT,PBF,PBFS,PBFX,PBH,PBHC,PBI,PBIP,PBPB,PBT,PBTS,PBYI,PCAR,PCB,PCG,PCH,PCOM,PCPL,PCRX,PCSB,PCTI,PCTY,PCVX,PCYG,PCYO,PD,PDCE,PDCO,PDEX,PDFS,PDLB,PDLI,PDM,PDS,PDSB&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 64 &
echo 64/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=PE,PEAK,PEB,PEBK,PEBO,PECK,PED,PEG,PEGA,PEI,PEIX,PEN,PENN,PEP,PER,PERI,PESI,PETQ,PETS,PETZ,PFBC,PFBI,PFC,PFE,PFG,PFGC,PFHD,PFIE,PFIN,PFIS,PFLT,PFMT,PFNX,PFPT,PFS,PFSI,PFSW,PG,PGC,PGEN,PGNY,PGR,PGRE,PGTI,PH,PHAS,PHAT,PHCF,PHGE&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 65 &
echo 65/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=PHIO,PHM,PHR,PHUN,PHX,PI,PIC,PICO,PIH,PII,PINC,PINE,PING,PINS,PIPR,PIRS,PIXY,PJT,PK,PKBK,PKE,PKG,PKI,PKOH,PLAB,PLAG,PLAN,PLAY,PLBC,PLCE,PLD,PLG,PLIN,PLM,PLMR,PLNT,PLOW,PLPC,PLRX,PLSE,PLT,PLUG,PLUS,PLX,PLXP,PLXS,PLYA,PLYM,PM&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 66 &
echo 66/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=PMBC,PMD,PME,PMT,PNBK,PNC,PNFP,PNM,PNNT,PNR,PNRG,PNTG,PNW,POAI,PODD,POLA,POOL,POR,POST,POWI,POWL,PPBI,PPC,PPD,PPG,PPHI,PPIH,PPL,PPSI,PQG,PRA,PRAA,PRAH,PRCP,PRDO,PRFT,PRGO,PRGS,PRGX,PRI,PRIM,PRK,PRLB,PRMW,PRNB,PRO,PROF,PROG,PROS&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 67 &
echo 67/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=PROV,PRPH,PRPL,PRPO,PRQR,PRSC,PRSP,PRT,PRTA,PRTH,PRTK,PRTS,PRTY,PRU,PRVB,PRVL,PS,PSA,PSB,PSEC,PSHG,PSMT,PSN,PSNL,PSTG,PSTI,PSTL,PSTV,PSTX,PSV,PSX,PSXP,PTAC,PTC,PTCT,PTE,PTEN,PTGX,PTI,PTMN,PTN,PTON,PTSI,PTVCA,PTVCB,PULM,PUMP,PVAC,PVBC&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 68 &
echo 68/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=PVG,PVH,PVL,PW,PWFL,PWOD,PWR,PXD,PXLW,PXS,PYPD,PYPL,PZG,PZN,PZZA,QADA,QADB,QCOM,QCRH,QDEL,QEP,QGEN,QLGN,QLYS,QMCO,QNST,QRHC,QRTEA,QRTEB,QRVO,QSR,QTNT,QTRX,QTS,QTWO,QUAD,QUIK,QUMU,QUOT,QURE,R,RACA,RACE,RAD,RADA,RAIL,RAMP,RAND,RAPT&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 69 &
echo 69/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=RARE,RAVE,RAVN,RBA,RBB,RBBN,RBC,RBCAA,RBCN,RBKB,RBNC,RC,RCEL,RCI,RCII,RCKT,RCKY,RCM,RCMT,RCON,RCUS,RDCM,RDFN,RDI,RDIB,RDN,RDNT,RDUS,RDVT,RDWR,RE,REAL,REED,REFR,REG,REGI,REGN,REI,REKR,RELL,RELV,REPH,REPL,RES,RESI,RESN,RETA,RETO,REV&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 70 &
echo 70/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=REVG,REX,REXN,REXR,REYN,REZI,RF,RFIL,RFL,RFP,RGA,RGCO,RGEN,RGLD,RGLS,RGNX,RGP,RGR,RGS,RH,RHE,RHI,RHP,RIBT,RICK,RIG,RIGL,RILY,RIOT,RIVE,RJF,RKDA,RKT,RL,RLAY,RLGT,RLGY,RLH,RLI,RLJ,RLMD,RM,RMAX,RMBI,RMBL,RMBS,RMCF,RMD,RMED&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 71 &
echo 71/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=RMG,RMNI,RMR,RMTI,RNA,RNDB,RNET,RNG,RNGR,RNR,RNST,RNWK,ROAD,ROCH,ROCK,ROG,ROIC,ROK,ROKU,ROL,ROLL,ROP,ROST,RP,RPAI,RPAY,RPD,RPLA,RPM,RPRX,RPT,RPTX,RRBI,RRC,RRD,RRGB,RRR,RS,RSG,RSSS,RST,RTLR,RTRX,RTX,RUBY,RUN,RUSHA,RUSHB,RUTH&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 72 &
echo 72/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=RVI,RVLV,RVMD,RVNC,RVP,RVSB,RWLK,RWT,RXN,RXT,RY,RYAM,RYCE,RYI,RYN,RYTM,SA,SABR,SACH,SAFE,SAFM,SAFT,SAGE,SAH,SAIA,SAIC,SAIL,SAL,SALM,SALT,SAM,SAMA,SAMG,SAND,SANM,SANW,SAQN,SAR,SASR,SATS,SAVA,SAVE,SB,SBAC,SBBP,SBCF,SBE,SBFG,SBGI&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 73 &
echo 73/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=SBH,SBLK,SBNY,SBOW,SBPH,SBR,SBRA,SBSI,SBT,SBUX,SC,SCCO,SCHL,SCHN,SCHW,SCI,SCKT,SCL,SCM,SCON,SCOR,SCPE,SCPH,SCPL,SCS,SCSC,SCU,SCVL,SCVX,SCWX,SCX,SCYX,SD,SDC,SDGR,SDPI,SEAC,SEAS,SEB,SEDG,SEE,SEED,SEEL,SEIC,SELB,SELF,SEM,SENEA,SENEB&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 74 &
echo 74/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=SENS,SERV,SESN,SF,SFBC,SFBS,SFE,SFIX,SFL,SFM,SFNC,SFST,SFTW,SG,SGA,SGBX,SGC,SGEN,SGH,SGLB,SGMA,SGMO,SGMS,SGOC,SGRP,SGRY,SGU,SHAK,SHBI,SHEN,SHIP,SHLL,SHLO,SHLX,SHO,SHOO,SHOP,SHSP,SHW,SHYF,SI,SIBN,SIC,SIEB,SIEN,SIF,SIG,SIGA,SIGI&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 75 &
echo 75/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=SII,SILC,SILK,SILV,SINA,SINO,SINT,SIRI,SITC,SITE,SITM,SIVB,SIX,SJ,SJI,SJM,SJR,SJT,SJW,SKT,SKX,SKY,SKYW,SLAB,SLB,SLCA,SLCT,SLDB,SLF,SLG,SLGG,SLGL,SLGN,SLM,SLNO,SLP,SLQT,SLRC,SLRX,SLS,SM,SMAR,SMBC,SMBK,SMCI,SMED,SMG,SMHI,SMIT&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 76 &
echo 76/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=SMLP,SMMC,SMMF,SMP,SMPL,SMRT,SMSI,SMTC,SMTS,SMTX,SNA,SNAP,SNBR,SNCA,SNCR,SND,SNDE,SNDL,SNDR,SNDX,SNES,SNEX,SNFCA,SNGX,SNMP,SNOA,SNPS,SNR,SNSS,SNV,SNX,SO,SOAC,SOHO,SOI,SOLO,SOLY,SON,SONA,SONM,SONN,SONO,SP,SPAQ,SPB,SPCB,SPCE,SPFI,SPG&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 77 &
echo 77/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=SPGI,SPH,SPI,SPKE,SPLK,SPLP,SPN,SPNE,SPNS,SPOK,SPOT,SPPI,SPR,SPRO,SPRT,SPSC,SPT,SPTN,SPWH,SPWR,SPXC,SQ,SQBG,SQFT,SR,SRAC,SRAX,SRC,SRCE,SRCL,SRDX,SRE,SREV,SRG,SRGA,SRI,SRL,SRLP,SRNE,SRPT,SRRA,SRRK,SRT,SRTS,SSB,SSBI,SSD,SSKN,SSNC&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 78 &
echo 78/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=SSNT,SSP,SSPK,SSRM,SSSS,SSTI,SSTK,SSY,SSYS,ST,STAA,STAF,STAG,STAR,STBA,STC,STCN,STE,STFC,STIM,STKL,STKS,STL,STLD,STMP,STN,STND,STNE,STNG,STOK,STON,STOR,STRA,STRL,STRM,STRO,STRS,STRT,STSA,STT,STWD,STX,STXB,STXS,STZ,STZ.B,SU,SUI,SUM&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 79 &
echo 79/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=SUMR,SUN,SUNS,SUNW,SUP,SUPN,SURF,SVA,SVBI,SVC,SVM,SVMK,SVRA,SVT,SWAV,SWBI,SWCH,SWI,SWIR,SWK,SWKH,SWKS,SWM,SWN,SWTX,SWX,SXC,SXI,SXT,SXTC,SYBT,SYBX,SYF,SYK,SYKE,SYN,SYNA,SYNC,SYNH,SYNL,SYPR,SYRS,SYX,SYY,T,TA,TAC,TACO,TACT&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 80 &
echo 80/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=TAIT,TALO,TANH,TAOP,TAP,TAP.A,TARA,TARO,TAST,TAT,TATT,TAYD,TBBK,TBI,TBIO,TBK,TBLT,TBNK,TBPH,TCBI,TCBK,TCCO,TCDA,TCF,TCFC,TCI,TCMD,TCO,TCON,TCP,TCPC,TCRR,TCS,TCX,TD,TDAC,TDC,TDG,TDOC,TDS,TDW,TDY,TEAM,TECH,TECK,TEL,TELA,TELL,TEN&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 81 &
echo 81/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=TENB,TENX,TER,TESS,TEUM,TEX,TFC,TFFP,TFII,TFSL,TFX,TG,TGA,TGB,TGC,TGH,TGI,TGLS,TGNA,TGP,TGT,TGTX,TH,THBR,THC,THCA,THCB,THFF,THG,THM,THMO,THO,THR,THRM,THS,THTX,TIF,TIG,TIGO,TILE,TIPT,TISI,TITN,TJX,TK,TKAT,TKR,TLF,TLGT&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 82 &
echo 82/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=TLRY,TLYS,TMBR,TMDI,TMDX,TMHC,TMO,TMP,TMQ,TMST,TMUS,TNAV,TNC,TNDM,TNET,TNK,TNP,TNXP,TOL,TOPS,TORC,TOTA,TOWN,TPB,TPC,TPCO,TPH,TPHS,TPIC,TPL,TPR,TPRE,TPTX,TPX,TR,TRC,TRCH,TREB,TREC,TREE,TREX,TRGP,TRHC,TRI,TRIL,TRIP,TRMB,TRMD,TRMK&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 83 &
echo 83/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=TRMT,TRN,TRNE,TRNO,TRNS,TROW,TROX,TRP,TRQ,TRS,TRST,TRT,TRTN,TRTX,TRU,TRUE,TRUP,TRV,TRVI,TRVN,TRWH,TRX,TRXC,TSBK,TSC,TSCO,TSE,TSEM,TSLX,TSN,TSQ,TSRI,TT,TTC,TTD,TTEC,TTEK,TTGT,TTI,TTMI,TTNP,TTOO,TTWO,TU,TUFN,TUP,TURN,TUSK,TVTY&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 84 &
echo 84/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=TW,TWI,TWIN,TWLO,TWMC,TWNK,TWO,TWOU,TWST,TWTR,TXG,TXMD,TXN,TXRH,TXT,TYHT,TYL,TYME,TZAC,TZOO,UA,UAA,UAL,UAMY,UAN,UAVS,UBA,UBCP,UBER,UBFO,UBOH,UBP,UBS,UBSI,UBX,UCBI,UCTT,UDR,UE,UEC,UEIC,UEPS,UFAB,UFCS,UFI,UFPI,UFPT,UFS,UG&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 85 &
echo 85/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=UGI,UHAL,UHS,UHT,UI,UIHC,UIS,ULBI,ULH,ULTA,UMBF,UMH,UMPQ,UMRX,UNAM,UNB,UNF,UNFI,UNH,UNIT,UNM,UNP,UNTY,UNVR,UONE,UONEK,UPLD,UPS,UPWK,URBN,URG,URGN,URI,UROV,USAC,USAK,USAP,USAS,USAU,USB,USCR,USDP,USEG,USFD,USIO,USLM,USM,USNA,USPH&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 86 &
echo 86/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=USWS,USX,UTHR,UTI,UTL,UTMD,UTSI,UUU,UUUU,UVE,UVSP,UVV,V,VAC,VAL,VALU,VAPO,VAR,VBFC,VBIV,VBLT,VBTX,VC,VCEL,VCNX,VCRA,VCTR,VCYT,VEC,VECO,VEEV,VEL,VER,VERB,VERI,VERO,VERU,VERX,VERY,VET,VFC,VFF,VG,VGR,VGZ,VHC,VHI,VIAC,VIACA&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 87 &
echo 87/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=VIAV,VICI,VICR,VIE,VIR,VIRC,VIRT,VISL,VITL,VIVE,VIVO,VKTX,VLGEA,VLO,VLY,VMC,VMD,VMI,VMW,VNCE,VNDA,VNE,VNO,VNOM,VNRX,VNTR,VOC,VOLT,VOXX,VOYA,VPG,VRA,VRAY,VRCA,VREX,VRM,VRME,VRNS,VRNT,VRRM,VRS,VRSK,VRSN,VRT,VRTS,VRTU,VRTV,VRTX,VSAT&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 88 &
echo 88/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=VSEC,VSH,VSLR,VST,VSTA,VSTM,VSTO,VTGN,VTNR,VTOL,VTR,VTSI,VTVT,VUZI,VVI,VVNT,VVPR,VVV,VXRT,VYGR,VZ,W,WAB,WABC,WAFD,WAFU,WAL,WASH,WAT,WATT,WBA,WBS,WBT,WCC,WCN,WD,WDAY,WDC,WDFC,WDR,WEC,WELL,WEN,WERN,WES,WETF,WEX,WEYS,WFC&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 89 &
echo 89/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=WGO,WH,WHD,WHF,WHG,WHLM,WHLR,WHR,WIFI,WILC,WINA,WING,WINS,WINT,WIRE,WISA,WIX,WK,WKHS,WLDN,WLFC,WLK,WLKP,WLL,WLTW,WM,WMB,WMC,WMG,WMGI,WMK,WMS,WMT,WNC,WNEB,WOR,WORK,WORX,WOW,WPC,WPF,WPG,WPM,WPRT,WPX,WRB,WRE,WRI,WRK&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 90 &
echo 90/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=WRLD,WRN,WRTC,WSBC,WSBF,WSC,WSFS,WSM,WSO,WSO.B,WSR,WST,WSTG,WSTL,WTBA,WTER,WTFC,WTI,WTM,WTRE,WTRG,WTRH,WTS,WTT,WTTR,WU,WVE,WVFC,WVVI,WW,WWD,WWE,WWR,WWW,WY,WYND,WYNN,WYY,X,XAIR,XAN,XBIO,XBIT,XCUR,XEC,XEL,XELA,XELB,XENE&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 91 &
echo 91/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=XENT,XERS,XFOR,XGN,XHR,XLNX,XLRN,XNCR,XOM,XOMA,XONE,XP,XPEL,XPER,XPL,XPO,XRAY,XRX,XSPA,XTNT,XXII,XYL,Y,YCBD,YELP,YETI,YEXT,YGYI,YMAB,YNDX,YORW,YRCW,YTEN,YTRA,YUM,YUMC,YVR,Z,ZAGG,ZBH,ZBRA,ZCMD,ZDGE,ZEN,ZEUS,ZG,ZGNX,ZGYH,ZI&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 92 &
echo 92/93
sleep 0.5
python3 /mnt/jfs/a/stockr-py/stockr-py/getquotes.py "https://sandbox-sse.iexapis.com/stable/stocksUSNoUTP?symbols=ZION,ZIOP,ZIXI,ZKIN,ZM,ZN,ZNGA,ZNTL,ZOM,ZS,ZSAN,ZTS,ZUMZ,ZUO,ZVO,ZYME,ZYNE,ZYXI,TSLA,AMD,FRD,FSDC,RCL,CVAC,DCT,FLUX,FUSE,AMHC,HRMY,INBX,KCAC,NYC,PTRS,MAXNV,GAN&token=Tpk_bc69ad6503f345cd9c0cb48dabf16b17" 93 &
echo 93/93
sleep 0.5
